//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICA.MailWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MailWebService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name to from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendmail1", ReplyAction="*")]
        ICA.MailWebService.sendmail1Response sendmail1(ICA.MailWebService.sendmail1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendmail1", ReplyAction="*")]
        System.Threading.Tasks.Task<ICA.MailWebService.sendmail1Response> sendmail1Async(ICA.MailWebService.sendmail1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendmail1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendmail1", Namespace="http://tempuri.org/", Order=0)]
        public ICA.MailWebService.sendmail1RequestBody Body;
        
        public sendmail1Request() {
        }
        
        public sendmail1Request(ICA.MailWebService.sendmail1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendmail1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string body;
        
        public sendmail1RequestBody() {
        }
        
        public sendmail1RequestBody(string to, string subject, string body) {
            this.to = to;
            this.subject = subject;
            this.body = body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendmail1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendmail1Response", Namespace="http://tempuri.org/", Order=0)]
        public ICA.MailWebService.sendmail1ResponseBody Body;
        
        public sendmail1Response() {
        }
        
        public sendmail1Response(ICA.MailWebService.sendmail1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendmail1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendmail1Result;
        
        public sendmail1ResponseBody() {
        }
        
        public sendmail1ResponseBody(string sendmail1Result) {
            this.sendmail1Result = sendmail1Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : ICA.MailWebService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ICA.MailWebService.WebServiceSoap>, ICA.MailWebService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ICA.MailWebService.sendmail1Response ICA.MailWebService.WebServiceSoap.sendmail1(ICA.MailWebService.sendmail1Request request) {
            return base.Channel.sendmail1(request);
        }
        
        public string sendmail1(string to, string subject, string body) {
            ICA.MailWebService.sendmail1Request inValue = new ICA.MailWebService.sendmail1Request();
            inValue.Body = new ICA.MailWebService.sendmail1RequestBody();
            inValue.Body.to = to;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            ICA.MailWebService.sendmail1Response retVal = ((ICA.MailWebService.WebServiceSoap)(this)).sendmail1(inValue);
            return retVal.Body.sendmail1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ICA.MailWebService.sendmail1Response> ICA.MailWebService.WebServiceSoap.sendmail1Async(ICA.MailWebService.sendmail1Request request) {
            return base.Channel.sendmail1Async(request);
        }
        
        public System.Threading.Tasks.Task<ICA.MailWebService.sendmail1Response> sendmail1Async(string to, string subject, string body) {
            ICA.MailWebService.sendmail1Request inValue = new ICA.MailWebService.sendmail1Request();
            inValue.Body = new ICA.MailWebService.sendmail1RequestBody();
            inValue.Body.to = to;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            return ((ICA.MailWebService.WebServiceSoap)(this)).sendmail1Async(inValue);
        }
    }
}
